# Generated by Django 4.1.5 on 2023-01-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.TextField(max_length=10),
        ),
    ]
